version = 1

[[annotations]]
path = [ "*.yml", "*.yaml", ".git*", "*.dist", "composer.*", ".github/*.yml", ".github/workflows/**.yml", "AGENTS.md" ]
SPDX-FileCopyrightText = "Respect Project Contributors"
SPDX-License-Identifier = "ISC"
